const { SalesInvoice, Ledger, Company, AuditLog, AppNotification, SystemMail } = require('../models');
const { Op } = require('sequelize');
const moment = require('moment');
const nodemailer = require('nodemailer');

class ReminderService {
  /**
   * Validates email format.
   */
  static isValidEmail(email) {
    if (!email) return false;
    const re = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return re.test(String(email).toLowerCase());
  }

  /**
   * Generates a professional HTML email template
   */
  static generateEmailTemplate(invoice, type, message) {
    const colors = {
      'UPCOMING': '#3b82f6', // Blue
      'OVERDUE': '#f59e0b',  // Orange
      'FINAL': '#ef4444'     // Red
    };
    
    const themeColor = colors[type] || '#3b82f6';
    const headerTitle = type === 'UPCOMING' ? 'Payment Reminder' : type === 'OVERDUE' ? 'Overdue Notice' : 'Final Notice';
    const companyName = invoice.Company?.name || 'Accounts Department';
    
    // Format currency to local string. Fallback to basic string if needed.
    const amountStr = Number(invoice.balance).toLocaleString('en-IN', { style: 'currency', currency: 'INR' });
    const dueDateStr = moment(invoice.dueDate).format('MMMM Do, YYYY');

    return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f3f4f6; margin: 0; padding: 20px; }
        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
        .header { background-color: ${themeColor}; color: #ffffff; padding: 20px; text-align: center; }
        .header h1 { margin: 0; font-size: 24px; font-weight: 600; }
        .content { padding: 30px; color: #374151; line-height: 1.6; }
        .details-table { width: 100%; border-collapse: collapse; margin-top: 20px; margin-bottom: 20px; }
        .details-table th, .details-table td { padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
        .details-table th { background-color: #f9fafb; font-weight: 600; color: #6b7280; width: 40%; }
        .footer { background-color: #f9fafb; padding: 20px; text-align: center; color: #9ca3af; font-size: 14px; border-top: 1px solid #e5e7eb; }
        .amount { font-size: 18px; font-weight: bold; color: ${themeColor}; }
        .pay-button { display: inline-block; background-color: ${themeColor}; color: #ffffff; text-decoration: none; padding: 12px 24px; border-radius: 4px; font-weight: bold; margin-top: 10px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>${headerTitle}</h1>
        </div>
        <div class="content">
          <p>${message.replace(/\\n/g, '<br/>')}</p>
          
          <table class="details-table">
            <tr>
              <th>Invoice Number</th>
              <td><strong>${invoice.invoiceNumber}</strong></td>
            </tr>
            <tr>
              <th>Due Date</th>
              <td>${dueDateStr}</td>
            </tr>
            <tr>
              <th>Amount Due</th>
              <td class="amount">${amountStr}</td>
            </tr>
          </table>

          <p>If you have already made the payment, please disregard this email.</p>
          <p>Thank you,<br/><strong>${companyName}</strong></p>
        </div>
        <div class="footer">
          This is an automated message generated by the Smart Payment Reminders system. Please do not reply directly to this email.
        </div>
      </div>
    </body>
    </html>
    `;
  }

  /**
   * Process all pending payment reminders
   */
  static async processPaymentReminders(companyId = null) {
    try {
      console.log('--- STARTING SMART PAYMENT REMINDERS ---');
      
      const whereClause = {
        status: { [Op.notIn]: ['Paid', 'Void'] },
        balance: { [Op.gt]: 0 },
        dueDate: { [Op.not]: null }
      };

      if (companyId) {
        whereClause.CompanyId = companyId;
      }

      const invoices = await SalesInvoice.findAll({
        where: whereClause,
        include: [
          { model: Ledger, as: 'CustomerLedger', attributes: ['id', 'name', 'email'] },
          { model: Company, attributes: ['id', 'name'] }
        ]
      });

      let sentCount = 0;
      let skippedCount = 0;
      let errorCount = 0;

      const today = moment().startOf('day');

      for (const invoice of invoices) {
        try {
          const dueDate = moment(invoice.dueDate).startOf('day');
          const daysDiff = today.diff(dueDate, 'days'); // + means overdue, - means upcoming

          let reminderType = null;
          let emailSubject = '';
          let emailBody = '';

          // RULES CONFIGURATION
          if (daysDiff === -3) {
            reminderType = 'UPCOMING';
            emailSubject = `Upcoming Payment Reminder: Invoice ${invoice.invoiceNumber}`;
            emailBody = `Dear ${invoice.CustomerLedger.name},\n\nThis is a friendly reminder that Invoice ${invoice.invoiceNumber} for ${invoice.balance} is due on ${dueDate.format('YYYY-MM-DD')}.`;
          } else if (daysDiff === 1) {
            reminderType = 'OVERDUE';
            emailSubject = `Overdue Notice: Invoice ${invoice.invoiceNumber}`;
            emailBody = `Dear ${invoice.CustomerLedger.name},\n\nYour Invoice ${invoice.invoiceNumber} for ${invoice.balance} was due yesterday. Please arrange for payment at your earliest convenience.`;
          } else if (daysDiff === 7) {
            reminderType = 'FINAL';
            emailSubject = `Final Notice: Invoice ${invoice.invoiceNumber}`;
            emailBody = `Dear ${invoice.CustomerLedger.name},\n\nYour Invoice ${invoice.invoiceNumber} for ${invoice.balance} is 7 days overdue. Please submit payment immediately.`;
          }

          // Not a milestone day
          if (!reminderType) {
            continue;
          }

          // Duplicate protection
          if (invoice.lastReminderType === reminderType) {
            console.log(`Skipping Invoice ${invoice.invoiceNumber}: ${reminderType} reminder already sent.`);
            skippedCount++;
            continue;
          }

          // Email Validation
          const customerEmail = invoice.CustomerLedger.email;
          if (!this.isValidEmail(customerEmail)) {
            const warningMsg = `Failed to send ${reminderType} reminder for Invoice ${invoice.invoiceNumber}. Invalid or missing email for customer ${invoice.CustomerLedger.name}.`;
            console.log(warningMsg);
            
            await AppNotification.create({
              message: warningMsg,
              type: 'WARNING',
              CompanyId: invoice.CompanyId
            });

            await AuditLog.create({
              action: 'REMINDER_FAILED',
              entityType: 'SalesInvoice',
              entityId: invoice.id,
              details: warningMsg,
              CompanyId: invoice.CompanyId
            });
            
            errorCount++;
            continue;
          }

          // DISPATCH EMAIL
          const smtpHost = process.env.SMTP_HOST || 'smtp.gmail.com';
          const smtpPort = process.env.SMTP_PORT ? parseInt(process.env.SMTP_PORT) : 587;
          const userEmail = process.env.SMTP_USER || process.env.MAIL_USER;
          const userPass = process.env.SMTP_PASS || process.env.MAIL_PASS;

          if (!userEmail || !userPass) {
             throw new Error('SMTP credentials are not configured on the server. Please define SMTP_USER and SMTP_PASS.');
          }

          const transporter = nodemailer.createTransport({
            host: smtpHost,
            port: smtpPort,
            secure: smtpPort === 465,
            auth: {
              user: userEmail,
              pass: userPass
            },
            tls: {
                rejectUnauthorized: false
            }
          });

          const htmlBody = this.generateEmailTemplate(invoice, reminderType, emailBody);

          const mailOptions = {
            from: userEmail,
            to: customerEmail,
            subject: emailSubject,
            text: emailBody, // plain text fallback
            html: htmlBody
          };

          await transporter.sendMail(mailOptions);
          
          await SystemMail.create({
            CompanyId: invoice.CompanyId,
            LedgerId: invoice.CustomerLedger.id,
            toEmail: customerEmail,
            fromEmail: userEmail,
            subject: emailSubject,
            body: emailBody,
            status: 'Sent',
            type: 'Reminder'
          });

          console.log(`\n📧 [EMAIL SENT SUCCESSFULLY] to: ${customerEmail}`);

          // Update Status
          invoice.lastReminderDate = new Date();
          invoice.lastReminderType = reminderType;
          invoice.reminderCount += 1;
          await invoice.save();

          // Log Success
          const successMsg = `Successfully sent ${reminderType} reminder for Invoice ${invoice.invoiceNumber} to ${customerEmail}.`;
          
          await AuditLog.create({
            action: 'REMINDER_SENT',
            entityType: 'SalesInvoice',
            entityId: invoice.id,
            details: successMsg,
            CompanyId: invoice.CompanyId
          });

          await AppNotification.create({
            message: `Sent ${reminderType} reminder to ${invoice.CustomerLedger.name} for Invoice ${invoice.invoiceNumber}.`,
            type: 'SUCCESS',
            CompanyId: invoice.CompanyId
          });

          sentCount++;

        } catch (err) {
          console.error(`Error processing reminder for Invoice ${invoice.id}:`, err);
          errorCount++;
        }
      }

      console.log(`--- REMINDERS COMPLETED | Sent: ${sentCount} | Skipped Dupes: ${skippedCount} | Errors/Invalid Emails: ${errorCount} ---`);
      
      return {
        success: true,
        sent: sentCount,
        skipped: skippedCount,
        errors: errorCount
      };

    } catch (error) {
      console.error('Fatal Error in ReminderService:', error);
      throw error;
    }
  }
}

module.exports = ReminderService;
